---
title: "Pagoda Peak"
author: "Joseph Bakita"
date: "3/14/2022"
output:
  html_document: default
---

```{r}
map = array(dim = 44)
map[1] = 1 #blue space
map[2] = 1
map[3] = 2 #red space
map[4] = 3 #rocket space
map[5] = 1
map[6] = 1
map[7] = 4 #mic
map[8] = 1
map[9] = 1
map[10] = 5 #DK
map[11] = 1
map[12] = 6 #gong
map[13] = 1
map[14] = 2
map[15] = 1
map[16] = 7 #duel
map[17] = 7
map[18] = 7
map[19] = 8 #waterfall
map[20] = 2
map[21] = 5
map[22] = 1
map[23] = 1
map[24] = 1
map[25] = 1
map[26] = 1
map[27] = 1
map[28] = 2
map[29] = 1
map[30] = 1
map[31] = 6
map[32] = 1
map[33] = 4
map[34] = 9 #Bowser
map[35] = 10 #Statue
map[36] = 1
map[37] = 2
map[38] = 1
map[39] = 10
map[40] = 1
map[41] = 1
map[42] = 11 #Throwback
map[43] = 1
map[44] = 0
```

```{r}
coins = array(data = 0, dim = 4)
players = data.frame(coins)
players$wins = 0

s = 1000

wins1 = array(data = 0, dim = s)
wins2 = array(data = 0, dim = s)
wins3 = array(data = 0, dim = s)
wins4 = array(data = 0, dim = s)
skill1 = array(data = 0, dim = s)
skill2 = array(data = 0, dim = s)
skill3 = array(data = 0, dim = s)
skill4 = array(data = 0, dim = s)
scoreboard = data.frame(wins1, wins2, wins3, wins4, skill1, skill2, skill3, skill4)



for (k in 1:s) {
  
scoreboard$turns[k] = 10 + 5*sample(1:8, 1)

for(i in 1:4) {
  players$skill[i] = runif(1, min=0)
}
players$skill=players$skill/sum(players$skill)
for(i in 5:8) {
  scoreboard[k,c(i)] = players$skill[i-4]
}           #Random Skill Generation + Scaling
    
players$stars = 0
players$item1 = 0
players$item2 = 0
players$item3 = 0
players$status = 0
players$place1 = 44
players$place2 = 0
star_price = 10
players$coins = 10

#for(i in 1:4) {
#  players$skill[i] = runif(1, min=0)
#  scoreboard[k,c(4+i)] = players$skill[i]
#}

for (i in 1:scoreboard$turns[k]) {
  for (j in 1:4) {
    roll = sample(1:10,1)
    if (players$status[j] == 1 | players$status[j] == 2) {
      players$place2[j] = (players$place1[j] + 2 * roll) %% 44 + 1
    } else {
      players$place2[j] = (players$place1[j] + roll) %% 44 + 1
    }
    
    if (players$place1[j] + roll > 43 & players$coins[j] >= star_price) {
      players$stars[j] = players$stars[j] + 1
      players$coins[j] = players$coins[j] - star_price
      star_price = star_price + 10          #Star purchase
      if (star_price > 40) star_price = star_price - 40
    }
    
    if (map[players$place2[j]]==1) {
      players$coins[j] = players$coins[j] + 3          #Landing on a blue space
    } else if (map[players$place2[j]]==2) {
      players$coins[j] = players$coins[j] - 3          #Landing on a red space
    } else if (map[players$place2[j]]==7) {
      
      t = 0 
      t1 = 0 #opponent's stars
      t2 = 0 #opponent's coins
      for(n in 1:4) {
        if(n != j) {  
          if (players$stars[n] > t1) {
            t = n
            t1 = players$stars[n]
            t2 = players$coins[n]
          } else if (players$stars[n] == t1 & players$coins[n] > t2) {
            t = n
            t2 = players$coins[n]
          }
        }
      }          #Choosing the most valuable opponent
      
      t3 = sample(1:5,1)
      t4 = rbinom(1,size=1, prob = players$skill[j]/(players$skill[j]+players$skill[t]))
      if (t3 == 2) {          #10 coins
        if (players$coins[j] >= 10 & t2 >= 10) {
          players$coins[j] = players$coins[j]-10 + 20*t4
          players$coins[t] = players$coins[t]+10 - 20*t4
        } else if (t4 == 1) {
          players$coins[j] = players$coins[j]+players$coins[t]
          players$coins[t] = 0
        } else {
          players$coins[t] = players$coins[j]+players$coins[t]
          players$coins[j] = 0
        }
          
      } else if (t3 == 3) {
        players$coins[t] = t4*(players$coins[j] + round(players$coins[t]/2))
        players$coins[j] = t4*(players$coins[j]+round(t2/2))
      } else if (t3 == 4) {          #All coins
        players$coins[t] = t4*(players$coins[j] + players$coins[t])
        players$coins[j] = t4*(players$coins[j]+t2)
      } else if (t3 == 5) {          #Star
        if (players$stars[j] > 0 & t4 == 0) {
          players$stars[j] = players$stars[j]-1
          players$stars[t] = players$stars[t]+1 
        } else if (players$stars[t] & t4==1) {
          players$stars[j] = players$stars[j]+1
          players$stars[t] = players$stars[t]-1 
        }
      }
      
    }          #Landing on a duel space
    
    players$place1[j] = players$place2[j]
    
  }
  if (rbinom(1,size=1,prob = players$skill[1])==1) {
    minigame = 1
  } else if (rbinom(1,size=1,prob = players$skill[2]/(players$skill[2]+players$skill[3]+players$skill[4]))==1) {
    minigame = 2
  } else if (rbinom(1,size=1,prob = players$skill[3]/(players$skill[3]+players$skill[4]))==1) {
    minigame = 3
  } else minigame = 4
  players$coins[minigame] = players$coins[minigame] + 10
}

for (j in 1:4) {
  t = 0
  for (m in 1:4) {
    if (players$stars[j] > players$stars[m]) {
      t = t + 1
    } else if (players$stars[j] == players$stars[m] & players$coins[j] > players$coins[m]) {
      t = t + 1
    }
    
  }
  if (t == 3) { 
    players$wins[j] = players$wins[j] + 1
    scoreboard[k, c(j)] = scoreboard[k, c(j)] + 1
    scoreboard$winner[k] = j
  }
  
}
}






```



```{r}
library(rethinking)

d <- list(
  win = scoreboard$wins1,
  skill = scoreboard$skill1,
  turns = scoreboard$turns/5-2
)

model <- ulam( alist(
  win ~ dbinom(1, p),
  logit(p) <- bs*skill + bt[turns],
  bs ~ dnorm(0, 1.5),
  bt[turns] ~ dnorm(0,1.5)
), data = d, chains = 4, log_lik=TRUE, cores = parallel::detectCores())

```

```{r}

precis(model, depth = 2)

post <- extract.samples(model)
win <- inv_logit( post$bt )
plot( precis( as.data.frame(win) ) )

#win <- inv_logit( post$bs )
#plot( precis( as.data.frame(win) ) , xlim=c(0,1) )

#plot(precis(model, depth =2))


```


```{r}

d2 <- list(
  win = scoreboard$wins4,
  skill = scoreboard$skill4,
  turns = scoreboard$turns/5-2
)

model2 <- ulam( alist(
  win ~ dbinom(1, p),
  logit(p) <- a[turns] + bs*skill,
  a[turns] ~ dnorm(0, 1.5),
  bs ~ dnorm(0, 1.5)
), data = d2, chains = 1, log_lik=TRUE)

```

```{r}

precis(model2, depth = 2)

post <- extract.samples(model2)
win <- inv_logit( post$a )
plot( precis( as.data.frame(win) ) )

#win <- inv_logit( post$bs )
#plot( precis( as.data.frame(win) ) , xlim=c(0,1) )

plot(precis(model2, depth =2))


```














































